TinhHoaSolutions-EzHR/chatbot

Makefile
docs/package.json
docs/pages/_meta.json
docs/pages/roadmap.mdx
docs/pnpm-lock.yaml

docs(roadmap): add milestone plan to roadmap documentation

---

.github/labeler.yml
.github/workflows/auto-labeler.yml
.github/workflows/automerge.yml

Add github actions for automerge and auto labeler.

ci(actions): add github actions for automerge

---

.gitignore
.pre-commit-config.yaml
chatbot-core/backend/app/databases/postgres.py
chatbot-core/backend/app/main.py
chatbot-core/backend/app/models/api.py
chatbot-core/backend/app/models/embedding_model.py
chatbot-core/backend/app/repositories/embeding_model.py
chatbot-core/backend/app/routers/base.py
chatbot-core/backend/app/routers/v1/embedding_model.py
chatbot-core/backend/app/services/embedding_model.py
chatbot-core/backend/app/settings/constants.py
chatbot-core/backend/app/utils/api_response.py

Update pre-commit hooks for python:
- Reorder python imports
- Autoflake
- Ruff: linter and formatter
**Summarize by Copilot**:
> This pull request includes several updates to the `chatbot-core/backend` project, focusing on improving import statements, updating pre-commit hooks, and enhancing code organization. The most important changes include updating the `.pre-commit-config.yaml` file, reordering and grouping import statements across multiple files, and updating dependencies.

hotfix(ci): update pre commit hooks for python

---

.github/workflows/pages.yml

Add github workflow yaml config to deploy onto github pages.

ci(docs): add github workflow yaml

---

chatbot-core/.env.example
chatbot-core/backend/app/databases/qdrant.py
chatbot-core/backend/app/settings/secrets.py
deployment/docker_compose/.env.example
deployment/docker_compose/docker-compose.dev.yaml

Hotfix document upload indexing pipeline when running inside Docker.

hotfix(backend): Document upload indexing pipeline

---

docs/blog/hardwareResourcing.mdx

Add documentation for hardware resourcing
#86

docs: add page for hardware resourcing

---

.github/workflows/docs-deploy.yml

fix(docs): add workflow dispatch to docs deploy

---

chatbot-core/EzHR-Chatbot.dbml

BREAKING CHANGE: add data catalog (dbml) file
View output at: https://dbdocs.io/lelouvincx/EzHR-Chatbot
#21

docs(database): add data catalog file

---

chatbot-core/frontend/i18n.js
chatbot-core/frontend/next.config.js
chatbot-core/frontend/package.json
chatbot-core/frontend/src/components/setLanguage.tsx
chatbot-core/frontend/yarn.lock

Add multilanguage support for the frontend. I haven't implemented a full language switcher yet. 
#43

feat(frontend): Chatbot multilanguage for frontend

---

chatbot-core/backend/app/models/agent.py
chatbot-core/backend/app/models/prompt.py
chatbot-core/backend/app/repositories/prompt.py

feat(backend): Add prompt repository layer

---

chatbot-core/backend/app/models/__init__.py
chatbot-core/backend/app/models/chat.py
chatbot-core/backend/app/repositories/chat.py
chatbot-core/backend/app/routers/v1/chat.py
chatbot-core/backend/app/services/chat.py

feat(backend): add endpoint for creating chat feedback

---

chatbot-core/backend/app/models/chat.py

hotfix(backend): change field `is_positive` of ChatFeedback model

---

chatbot-core/backend/app/utils/api/helpers.py

Currently, out api server container has no colored logs, so it is very difficult to distinguish between each level of logs. So, it is ideal to make logs colored.

feat(backend): Add colored logging feature

---

chatbot-core/frontend-v2/.eslintrc.json
chatbot-core/frontend-v2/package.json
chatbot-core/frontend-v2/src/components/new-chat-button.tsx
chatbot-core/frontend-v2/src/components/ui/avatar.tsx
chatbot-core/frontend-v2/src/components/ui/dropdown-menu.tsx
chatbot-core/frontend-v2/src/views/chat-page/header-logo.tsx
chatbot-core/frontend-v2/src/views/chat-page/user-button/user-button.tsx
chatbot-core/frontend-v2/src/views/chat-page/user-button/user-dropdown-item.tsx
chatbot-core/frontend-v2/src/views/main-layout/main-layout.tsx
chatbot-core/frontend-v2/tailwind.config.ts
chatbot-core/frontend-v2/yarn.lock

feat(frontend): add user button dropdown

---

chatbot-core/backend/app/models/provider.py
chatbot-core/backend/app/services/provider.py

Modify provider models to include a list of models

feat(backend): modify provider models to include a list of models

---

chatbot-core/backend/app/routers/v1/chat.py
chatbot-core/backend/app/services/chat.py

Add id return when creating chat session.

feat(backend): Add id return when creating chat session.

---

chatbot-core/frontend-v2/src/hooks/use-api-health-check.ts
chatbot-core/frontend-v2/src/lib/axios.ts
chatbot-core/frontend-v2/src/services/user/get-current-user.ts
chatbot-core/frontend-v2/src/services/user/get-user-oauth-access-token.ts
chatbot-core/frontend-v2/src/utils/get-api-url.ts

refactor(frontend): refactor frontend api call

---

chatbot-core/backend/app/repositories/folder.py
chatbot-core/backend/app/services/folder.py

chore: Modify folder update logic

---

chatbot-core/backend/app/models/user.py
chatbot-core/backend/app/repositories/user.py
chatbot-core/backend/app/routers/auth.py
chatbot-core/backend/app/routers/v1/user.py
chatbot-core/backend/app/services/user.py

Add user settings creation feature.

feat(backend): Add user settings creation feature

---

chatbot-core/backend/app/models/document.py
chatbot-core/backend/app/routers/v1/connector.py
chatbot-core/backend/app/services/document.py

fix document upload wrong output response

fix(backend): fix document upload wrong output response

---

chatbot-core/backend/app/models/chat.py
chatbot-core/backend/app/repositories/chat.py
chatbot-core/backend/app/routers/v1/chat.py
chatbot-core/backend/app/services/chat.py
chatbot-core/backend/app/utils/api/error_handler.py
chatbot-core/backend/pyproject.toml
chatbot-core/backend/uv.lock
deployment/docker_compose/docker-compose.dev.yaml

Implement sse streaming response

feat(backend): implement sse streaming response

---

deployment/docker_compose/docker-compose.dev.yaml

Fix invalid environment file configuration in docker-compose.dev.yaml

fix(docker): invalid env file in docker compose dev

---

.github/labeler.yml
.pre-commit-config.yaml

Add a new pre-commit hook to check for commit message's naming convention.

ci(pre-commit): add hook to check commit message's naming convention

---

chatbot-core/frontend/src/components/chat-message/chat-message.css
chatbot-core/frontend/src/components/chat-session-item/chat-session-button.tsx
chatbot-core/frontend/src/components/user-button/user-button.tsx
chatbot-core/frontend/src/views/main-layout/app-sidebar/app-sidebar-header.tsx
chatbot-core/frontend/src/views/main-layout/app-sidebar/app-sidebar.tsx
chatbot-core/frontend/src/views/main-layout/app-sidebar/chat-folders/chat-folder-item.tsx
chatbot-core/frontend/src/views/main-layout/app-sidebar/chat-history/chat-history.tsx
chatbot-core/frontend/src/views/main-layout/navbar/navbar.tsx

feat(frontend): hide unsupported feature

---

backend/app/main.py

Added `localhost:3000` to origins list.
Build and run with Docker.
None

Fix localhost blocked by CORS on windows systems

---

backend/app/settings/constants.py

- Correct the app's description data type
___
- Fix app description data type
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>constants.py</strong><dd><code>Correct app description data type</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
backend/app/settings/constants.py
- Changed `FASTAPI_DESCRIPTION` from tuple to string
</details>
</td>
<td><a href="https://github.com/TinhHoaSolutions-EzHR/chatbot/pull/291/files#diff-dd57704ebcb944ed4318ce6ac932c938a041a32c55f9ea787e3c0b48422f9d22">+1/-1</a>&nbsp; &nbsp; &nbsp; </td> …

fix(backend): correct app description data type
